version: '3.7'
services:
  frontend:
    restart: always
    env_file:
      - .env
    build:
      context: .
    ports:
      - "$PORT:$PORT"
    networks:
      - crypto

networks:
  crypto:
    driver: bridge



